import type { Metadata } from "next";
import { Inter } from "next/font/google";
import axios from "axios";
import "./globals.css";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

axios.defaults.baseURL = process.env.API_URL;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <TooltipProvider
                        delayDuration={200}
                        skipDelayDuration={500}
                    >
                        {children}
                    </TooltipProvider>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
